[project]
name = "fast-food-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "daphne>=4.2.1",
    "django>=5.2.4",
    "psycopg2>=2.9.10",
    "python-decouple>=3.8",
]
